version: '3.4'

services:
  k8s-cluster-comparator:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - './secret/kubeconfig_nvc.yaml:/kubeconfig1.yaml'
      - './secret/kubeconfig_rvc.yaml:/kubeconfig2.yaml'
    environment:
      NAMESPACES: ns1,ns2,...
      KUBECONFIG1: /kubeconfig1.yaml
      KUBECONFIG2: /kubeconfig2.yaml
      SKIP: deployment:whoami-11,whoami-24;daemonset:whoami-0,whoami-8
      DEBUG: "true"
