apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
              {{- toYaml . | nindent 8 }}
          {{- end }}
            serviceAccountName: {{ template "..serviceAccountName" . }}
            securityContext:
              {{- toYaml .Values.podSecurityContext | nindent 14 }}
            containers:
              - name: {{ .Chart.Name }}
                securityContext:
                  {{- toYaml .Values.securityContext | nindent 18 }}
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                resources:
                  {{- toYaml .Values.resources | nindent 18 }}
                volumeMounts:
                  - mountPath: /configs/
                    name: configs
            restartPolicy: Never
            {{- with .Values.nodeSelector }}
            nodeSelector:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.affinity }}
            affinity:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.tolerations }}
            tolerations:
              {{- toYaml . | nindent 14 }}
          {{- end }}
            volumes:
              - name: configs
                secret:
                  secretName: {{ include "..fullname" . }}
