apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
data:
  KUBECONFIG1.yaml: {{ .Values.kubeConfig1 | toYaml | b64enc | quote }}
  KUBECONFIG2.yaml: {{ .Values.kubeConfig2 | toYaml | b64enc | quote }}
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
type: Opaque
