name: Branch CI

on:
  push:
    branches-ignore:
      - 'master'
#    paths:
#      - '.github/workflows/branch-build.yml'

jobs:
  branch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.27.0

      - name: test and lint app
        run: |
          go test -race -timeout=60s -v ./internal/kubernetes/...
          $GITHUB_WORKSPACE/golangci-lint --config ${GITHUB_WORKSPACE}/.golangci.github.yml run --out-format=github-actions ./cmd/app/...
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "Europe/Moscow"

