name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag comparescript:$(date +%s)

    - name: Login in DockerHub
      run: docker login -e ${{secrets.LOGIN_DOCKERHUB}} -u ${{secrets.USER_NAME_DOCKERHUB}} -p ${{secrets.USER_PASSWORD_DOCKERHUB}}

    - name: Push Docker image on DockerHub
      run: docker push comparescript:$(date +%s)