name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      #    - name: Get dependencies
      #      run: |
      #        go get -v -t -d ./...
      #        if [ -f Gopkg.toml ]; then
      #            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      #            dep ensure
      #        fi

      - name: Test
        run: go test -v .

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sanekkurt/comparescript:latest

    - name: Login in DockerHub
      run: docker login -u ${{secrets.USER_NAME_DOCKERHUB}} -p ${{secrets.USER_PASSWORD_DOCKERHUB}}

    - name: Push Docker image on DockerHub
      run: docker push sanekkurt/comparescript:latest

