name: Git Tag Build

on:
  push:
    tags:
      - v*
    paths:
      - '.github/workflows/git-tag-build.yml'

jobs:
  tag-build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{secrets.USER_NAME_DOCKERHUB}}/k8s-cluster-comparator:${{ github.ref }}

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -v .

      - name: Login in DockerHub
        run: docker login -u ${{secrets.USER_NAME_DOCKERHUB}} -p ${{secrets.USER_PASSWORD_DOCKERHUB}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}

      - name: Push Docker image on DockerHub
        run: docker push ${DOCKER_IMAGE}
